import {
  AlertCircle,
  BarChart3,
  Boxes,
  CreditCard,
  Folder,
  Image as ImageIcon,
  ListChecks,
  MessageSquare,
  PackageX,
  Send,
  ShieldCheck,
  Sparkles,
  Store,
  Tag,
  Truck,
  Users,
} from "lucide-react";

export const ADMIN_DASHBOARD_MODULES = [
  {
    label: "Phân tích",
    href: "/admin/analytics",
    icon: BarChart3,
    desc: "GMV, người dùng, hoàn trả, KYC",
  },
  {
    label: "Người dùng",
    href: "/admin/users",
    icon: Users,
    desc: "Vai trò, trạng thái, mở khóa",
  },
  {
    label: "Duyệt KYC",
    href: "/admin/kyc",
    icon: ShieldCheck,
    desc: "Duyệt hoặc từ chối hồ sơ",
  },
  {
    label: "Phản hồi",
    href: "/admin/feedbacks",
    icon: MessageSquare,
    desc: "Trả lời và đổi trạng thái",
  },
  {
    label: "Trả hàng",
    href: "/admin/orders/returns",
    icon: PackageX,
    desc: "Override khi merchant treo",
  },
  {
    label: "Sản phẩm chờ duyệt",
    href: "/admin/products/pending",
    icon: ListChecks,
    desc: "Publish, reject, takedown",
  },
  {
    label: "Nhà bán",
    href: "/admin/merchants",
    icon: Store,
    desc: "Suspend, activate, đóng",
  },
  {
    label: "Thương hiệu",
    href: "/admin/brands",
    icon: Tag,
    desc: "Quản lý brand",
  },
  {
    label: "Danh mục",
    href: "/admin/categories",
    icon: Folder,
    desc: "Cây danh mục sản phẩm",
  },
  {
    label: "Kho hàng",
    href: "/admin/inventory",
    icon: Boxes,
    desc: "Tồn kho, khóa khẩn cấp",
  },
  {
    label: "Thanh toán",
    href: "/admin/payments",
    icon: CreditCard,
    desc: "Tra cứu, hoàn tiền",
  },
  {
    label: "Phí vận chuyển",
    href: "/admin/shipping/rates",
    icon: Truck,
    desc: "Rate theo zone",
    roles: ["SYSTEM_ADMIN"],
  },
  {
    label: "Banner khuyến mãi",
    href: "/admin/promotions/banners",
    icon: ImageIcon,
    desc: "Banner trang chủ",
  },
  {
    label: "Campaigns",
    href: "/admin/promotions/campaigns",
    icon: Sparkles,
    desc: "Khuyến mãi, voucher",
    roles: ["SYSTEM_ADMIN"],
  },
  {
    label: "Mẫu thông báo",
    href: "/admin/notifications/templates",
    icon: AlertCircle,
    desc: "Email, push templates",
    roles: ["SYSTEM_ADMIN"],
  },
  {
    label: "Notification provider",
    href: "/admin/notifications/providers",
    icon: Send,
    desc: "Cấu hình kênh gửi",
    roles: ["SYSTEM_ADMIN"],
  },
];
